version: "3"
services:
  nginx:
    container_name: consul
    image: consul:1.12.2
    environment:
      - USER_UID=1000
    ports:
      - 8500:8500
    volumes:
      - consul-data:/consul/data
    command: "agent -server -bootstrap -ui -node=server-test-1 -datacenter=dc_test1 -bind=127.0.0.1 -client='0.0.0.0'"
    restart: always
    cpus: 1
    mem_limit: 512M
    networks:
      - idatafun-net

networks:
  idatafun-net:
    external:
      name: idatafun

volumes:
  consul-data:
    name: consul