version: "3"
services:
  gitea_server:
    container_name: gitea
    image: gitea/gitea:1.17.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql-platform:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    cpus: 1
    mem_limit: 512M
    networks:
      - idatafun-net

networks:
  idatafun-net:
    external:
      name: idatafun

volumes:
  gitea-data:
    name: gitea
