version: "3"
services:
  portainer:
    container_name: portainer-ce
    image: portainer/portainer-ce:2.15.1
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-ce:/data
    restart: always
    cpus: 0.5
    mem_limit: 512M

volumes:
  portainer-ce:
    name: portainer-ce