version: "3"
services:
  # nginx网关
  nginx:
    image: nginx:1.19
    ports:
      - 81:80
    volumes:
      - /home/idatafun/docker/nginx:/etc/nginx
      - /home/idatafun/docker/web:/web
      - /tmp/idatafun:/tmp/idatafun
      - /data:/data
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: none
  # Consul配置中心
  consul:
    image: consul:1.12.2
    ports:
      - 8500:8500
    volumes:
      - consul-data:/consul/data
    command: "agent -server -bootstrap -ui -node=server-test-1 -datacenter=dc_test1 -bind=127.0.0.1 -client='0.0.0.0'"
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: none
  # MySQL平台使用数据库
  mysql-platform:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=8a155a5a549a482685eb60605116f2c8
      - TZ=Asia/Shanghai
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 100M
      restart_policy:
        condition: none
  # MySQL业务使用数据库
  mysql-business:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ee22d73f738c4f9995af6666e9c48093
      - TZ=Asia/Shanghai
    ports:
      - 3308:3306
    volumes:
      - mysql-business-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 100M
      restart_policy:
        condition: none
  # Redis业务使用数据库
  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 100M
      restart_policy:
        condition: none

networks:
  idatafun-swarm:
    external:
      name: idatafun-swarm

volumes:
  consul-data:
    external:
      name: consul-data
  mysql-data:
    external:
      name: mysql-platform-data
  mysql-business-data:
    external:
      name: mysql-business-data
  redis-data:
    external:
      name: redis-data
