version: "3"
services:
  # Gitea代码仓库管理
  gitea:
    image: gitea/gitea:1.17.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_DOMAIN=idatafun.com
      - SSH_PORT=10023
      - SSH_LISTEN_PORT=22
      - ROOT_URL=http://gitea.idatafun.com/
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=10.8.0.10:3307
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    ports:
      - 3000:3000
      - 10023:22
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: none
  # Drone持续集成服务器
  drone:
    image: drone/drone:latest
    environment:
      DRONE_GITEA_SERVER: http://gitea.idatafun.com
      DRONE_GITEA_CLIENT_ID: 7d89c97f-107c-42f0-9724-c54faf88328f
      DRONE_GITEA_CLIENT_SECRET: gto_2bkcarviwxxvdnnslv27ri3jky5lgsm6icfrsn7tue3gq3om7zfq
      DRONE_RPC_SECRET: 2994C253-FA1A-49A3-B5FB-F946E98ECF57
      DRONE_SERVER_HOST: drone.idatafun.com
      DRONE_SERVER_PROTO: http
      DRONE_USER_CREATE: username:AiJiangnan,admin:true
      DRONE_WEBHOOK_ENDPOINT: http://10.8.0.10:9080/api/webhook/drone
      DRONE_WEBHOOK_SECRET: bea26a2221fd8090ea38720fc445eca6
    ports:
      - 3001:80
    volumes:
      - drone-data:/data
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 50M
      restart_policy:
        condition: none
  # Drone Docker Runner
  drone-runner-docker:
    image: drone/drone-runner-docker:linux-amd64
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: 10.8.0.10:3001
      DRONE_RPC_SECRET: 2994C253-FA1A-49A3-B5FB-F946E98ECF57
      DRONE_RUNNER_NAME: drone-runner-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 50M
      restart_policy:
        condition: none
  # Drone SSH Runner
  drone-runner-ssh:
    image: drone/drone-runner-ssh:linux-amd64
    environment:
      DRONE_RPC_HOST: 10.8.0.10:3001
      DRONE_RPC_SECRET: 2994C253-FA1A-49A3-B5FB-F946E98ECF57
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 50M
      restart_policy:
        condition: none

networks:
  idatafun-swarm:
    external:
      name: idatafun-swarm

volumes:
  gitea-data:
    external:
      name: gitea-data
  drone-data:
    external:
      name: drone-data
