version: "3"
services:
  portainer-ce:
    image: portainer/portainer-ce:2.16.1
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-ce:/data
    networks:
      - idatafun-swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname==idatafun
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: none

networks:
  idatafun-swarm:
    external:
      name: idatafun-swarm

volumes:
  portainer-ce:
    external:
      name: portainer-ce-data
